### ISSUE TITLE
Android license not accepted

### ISSUE THREAD

**Issue by alorma** [vgaidarji/android-github-actions#10]
`> Failed to install the following Android SDK packages as some licences have not been accepted.`

https://github.com/alorma/RAC1/runs/191948302

**Comment by vgaidarji** [comment]
@alorma thanks. That's because Docker image used doesn't contain all possible Android SDKs installed and licenses.
To fix that I either need to accept more licenses (or run `sdkmanager` command instead to accept all licenses) or you'll need to fork base https://github.com/vgaidarji/docker-android/blob/master/docker-android-build image and install version of dependencies required for your builds.

`Android SDK Build Tools 28.0.3` is not currently installed  https://github.com/vgaidarji/docker-android/blob/master/docker-android-build/Dockerfile#L48.
